apiVersion: app.kiegroup.org/v1alpha1
kind: ServerlessOrchestrationApp
metadata:
  name: example-serverlessorchestrationapp
spec:
  name: test-app
  image: httpd:2.4
  definition: "12345678 test test"
  ports:
    - name: http
      protocol: TCP
      containerPort: 80
